# Generated by Django 5.2.11 on 2026-02-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.CharField(choices=[('basic', 'Cơ bản'), ('pro', 'Chuyên nghiệp')], default='basic', max_length=20),
        ),
    ]
