# Generated by Django 5.2.11 on 2026-02-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(upload_to='tts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
