# Generated by Django 5.2.11 on 2026-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0002_ttsrecord_user_speechtotext_speechurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsrecord',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ttsrecord',
            name='voice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
