# Generated by Django 5.2.11 on 2026-03-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0004_uploadedaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10)),
                ('image', models.ImageField(upload_to='voices/')),
                ('sample_audio', models.FileField(upload_to='voice_samples/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
